// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPathExtractor creates a new instance of MockPathExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathExtractor[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathExtractor[T] {
	mock := &MockPathExtractor[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPathExtractor is an autogenerated mock type for the PathExtractor type
type MockPathExtractor[T any] struct {
	mock.Mock
}

type MockPathExtractor_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockPathExtractor[T]) EXPECT() *MockPathExtractor_Expecter[T] {
	return &MockPathExtractor_Expecter[T]{mock: &_m.Mock}
}

// ExtractPath provides a mock function for the type MockPathExtractor
func (_mock *MockPathExtractor[T]) ExtractPath(t T, path string) (any, error) {
	ret := _mock.Called(t, path)

	if len(ret) == 0 {
		panic("no return value specified for ExtractPath")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(T, string) (any, error)); ok {
		return returnFunc(t, path)
	}
	if returnFunc, ok := ret.Get(0).(func(T, string) any); ok {
		r0 = returnFunc(t, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(T, string) error); ok {
		r1 = returnFunc(t, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPathExtractor_ExtractPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractPath'
type MockPathExtractor_ExtractPath_Call[T any] struct {
	*mock.Call
}

// ExtractPath is a helper method to define mock.On call
//   - t
//   - path
func (_e *MockPathExtractor_Expecter[T]) ExtractPath(t interface{}, path interface{}) *MockPathExtractor_ExtractPath_Call[T] {
	return &MockPathExtractor_ExtractPath_Call[T]{Call: _e.mock.On("ExtractPath", t, path)}
}

func (_c *MockPathExtractor_ExtractPath_Call[T]) Run(run func(t T, path string)) *MockPathExtractor_ExtractPath_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T), args[1].(string))
	})
	return _c
}

func (_c *MockPathExtractor_ExtractPath_Call[T]) Return(v any, err error) *MockPathExtractor_ExtractPath_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockPathExtractor_ExtractPath_Call[T]) RunAndReturn(run func(t T, path string) (any, error)) *MockPathExtractor_ExtractPath_Call[T] {
	_c.Call.Return(run)
	return _c
}
