// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"github.com/dgraph-io/badger/v4"
	"github.com/ehsanranjbar/badgerutils/store/ext"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExtension creates a new instance of MockExtension. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtension[K any, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtension[K, V] {
	mock := &MockExtension[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExtension is an autogenerated mock type for the Extension type
type MockExtension[K any, V any] struct {
	mock.Mock
}

type MockExtension_Expecter[K any, V any] struct {
	mock *mock.Mock
}

func (_m *MockExtension[K, V]) EXPECT() *MockExtension_Expecter[K, V] {
	return &MockExtension_Expecter[K, V]{mock: &_m.Mock}
}

// Instantiate provides a mock function for the type MockExtension
func (_mock *MockExtension[K, V]) Instantiate(txn *badger.Txn) ext.ExtensionInstance[K, V] {
	ret := _mock.Called(txn)

	if len(ret) == 0 {
		panic("no return value specified for Instantiate")
	}

	var r0 ext.ExtensionInstance[K, V]
	if returnFunc, ok := ret.Get(0).(func(*badger.Txn) ext.ExtensionInstance[K, V]); ok {
		r0 = returnFunc(txn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ext.ExtensionInstance[K, V])
		}
	}
	return r0
}

// MockExtension_Instantiate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Instantiate'
type MockExtension_Instantiate_Call[K any, V any] struct {
	*mock.Call
}

// Instantiate is a helper method to define mock.On call
//   - txn
func (_e *MockExtension_Expecter[K, V]) Instantiate(txn interface{}) *MockExtension_Instantiate_Call[K, V] {
	return &MockExtension_Instantiate_Call[K, V]{Call: _e.mock.On("Instantiate", txn)}
}

func (_c *MockExtension_Instantiate_Call[K, V]) Run(run func(txn *badger.Txn)) *MockExtension_Instantiate_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*badger.Txn))
	})
	return _c
}

func (_c *MockExtension_Instantiate_Call[K, V]) Return(extensionInstance ext.ExtensionInstance[K, V]) *MockExtension_Instantiate_Call[K, V] {
	_c.Call.Return(extensionInstance)
	return _c
}

func (_c *MockExtension_Instantiate_Call[K, V]) RunAndReturn(run func(txn *badger.Txn) ext.ExtensionInstance[K, V]) *MockExtension_Instantiate_Call[K, V] {
	_c.Call.Return(run)
	return _c
}
