// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPathExtractor is an autogenerated mock type for the PathExtractor type
type MockPathExtractor[T any, U any] struct {
	mock.Mock
}

type MockPathExtractor_Expecter[T any, U any] struct {
	mock *mock.Mock
}

func (_m *MockPathExtractor[T, U]) EXPECT() *MockPathExtractor_Expecter[T, U] {
	return &MockPathExtractor_Expecter[T, U]{mock: &_m.Mock}
}

// ExtractPath provides a mock function with given fields: t, path
func (_m *MockPathExtractor[T, U]) ExtractPath(t T, path string) (U, error) {
	ret := _m.Called(t, path)

	if len(ret) == 0 {
		panic("no return value specified for ExtractPath")
	}

	var r0 U
	var r1 error
	if rf, ok := ret.Get(0).(func(T, string) (U, error)); ok {
		return rf(t, path)
	}
	if rf, ok := ret.Get(0).(func(T, string) U); ok {
		r0 = rf(t, path)
	} else {
		r0 = ret.Get(0).(U)
	}

	if rf, ok := ret.Get(1).(func(T, string) error); ok {
		r1 = rf(t, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPathExtractor_ExtractPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractPath'
type MockPathExtractor_ExtractPath_Call[T any, U any] struct {
	*mock.Call
}

// ExtractPath is a helper method to define mock.On call
//   - t T
//   - path string
func (_e *MockPathExtractor_Expecter[T, U]) ExtractPath(t interface{}, path interface{}) *MockPathExtractor_ExtractPath_Call[T, U] {
	return &MockPathExtractor_ExtractPath_Call[T, U]{Call: _e.mock.On("ExtractPath", t, path)}
}

func (_c *MockPathExtractor_ExtractPath_Call[T, U]) Run(run func(t T, path string)) *MockPathExtractor_ExtractPath_Call[T, U] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T), args[1].(string))
	})
	return _c
}

func (_c *MockPathExtractor_ExtractPath_Call[T, U]) Return(_a0 U, _a1 error) *MockPathExtractor_ExtractPath_Call[T, U] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPathExtractor_ExtractPath_Call[T, U]) RunAndReturn(run func(T, string) (U, error)) *MockPathExtractor_ExtractPath_Call[T, U] {
	_c.Call.Return(run)
	return _c
}

// NewMockPathExtractor creates a new instance of MockPathExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPathExtractor[T any, U any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPathExtractor[T, U] {
	mock := &MockPathExtractor[T, U]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
