// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValueRetriever creates a new instance of MockValueRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValueRetriever[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValueRetriever[T] {
	mock := &MockValueRetriever[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValueRetriever is an autogenerated mock type for the ValueRetriever type
type MockValueRetriever[T any] struct {
	mock.Mock
}

type MockValueRetriever_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockValueRetriever[T]) EXPECT() *MockValueRetriever_Expecter[T] {
	return &MockValueRetriever_Expecter[T]{mock: &_m.Mock}
}

// Paths provides a mock function for the type MockValueRetriever
func (_mock *MockValueRetriever[T]) Paths() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Paths")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockValueRetriever_Paths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Paths'
type MockValueRetriever_Paths_Call[T any] struct {
	*mock.Call
}

// Paths is a helper method to define mock.On call
func (_e *MockValueRetriever_Expecter[T]) Paths() *MockValueRetriever_Paths_Call[T] {
	return &MockValueRetriever_Paths_Call[T]{Call: _e.mock.On("Paths")}
}

func (_c *MockValueRetriever_Paths_Call[T]) Run(run func()) *MockValueRetriever_Paths_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockValueRetriever_Paths_Call[T]) Return(strings []string) *MockValueRetriever_Paths_Call[T] {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockValueRetriever_Paths_Call[T]) RunAndReturn(run func() []string) *MockValueRetriever_Paths_Call[T] {
	_c.Call.Return(run)
	return _c
}

// RetrieveValue provides a mock function for the type MockValueRetriever
func (_mock *MockValueRetriever[T]) RetrieveValue(v *T) ([]byte, error) {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveValue")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*T) ([]byte, error)); ok {
		return returnFunc(v)
	}
	if returnFunc, ok := ret.Get(0).(func(*T) []byte); ok {
		r0 = returnFunc(v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*T) error); ok {
		r1 = returnFunc(v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockValueRetriever_RetrieveValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveValue'
type MockValueRetriever_RetrieveValue_Call[T any] struct {
	*mock.Call
}

// RetrieveValue is a helper method to define mock.On call
//   - v
func (_e *MockValueRetriever_Expecter[T]) RetrieveValue(v interface{}) *MockValueRetriever_RetrieveValue_Call[T] {
	return &MockValueRetriever_RetrieveValue_Call[T]{Call: _e.mock.On("RetrieveValue", v)}
}

func (_c *MockValueRetriever_RetrieveValue_Call[T]) Run(run func(v *T)) *MockValueRetriever_RetrieveValue_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T))
	})
	return _c
}

func (_c *MockValueRetriever_RetrieveValue_Call[T]) Return(bytes []byte, err error) *MockValueRetriever_RetrieveValue_Call[T] {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockValueRetriever_RetrieveValue_Call[T]) RunAndReturn(run func(v *T) ([]byte, error)) *MockValueRetriever_RetrieveValue_Call[T] {
	_c.Call.Return(run)
	return _c
}
