// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery

package mocks

import (
	"github.com/ehsanranjbar/badgerutils"
	"github.com/ehsanranjbar/badgerutils/indexing"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIndexer creates a new instance of MockIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexer[T] {
	mock := &MockIndexer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexer is an autogenerated mock type for the Indexer type
type MockIndexer[T any] struct {
	mock.Mock
}

type MockIndexer_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockIndexer[T]) EXPECT() *MockIndexer_Expecter[T] {
	return &MockIndexer_Expecter[T]{mock: &_m.Mock}
}

// Index provides a mock function for the type MockIndexer
func (_mock *MockIndexer[T]) Index(v *T, set bool) ([]badgerutils.RawKVPair, error) {
	ret := _mock.Called(v, set)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 []badgerutils.RawKVPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*T, bool) ([]badgerutils.RawKVPair, error)); ok {
		return returnFunc(v, set)
	}
	if returnFunc, ok := ret.Get(0).(func(*T, bool) []badgerutils.RawKVPair); ok {
		r0 = returnFunc(v, set)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]badgerutils.RawKVPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*T, bool) error); ok {
		r1 = returnFunc(v, set)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexer_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockIndexer_Index_Call[T any] struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - v
//   - set
func (_e *MockIndexer_Expecter[T]) Index(v interface{}, set interface{}) *MockIndexer_Index_Call[T] {
	return &MockIndexer_Index_Call[T]{Call: _e.mock.On("Index", v, set)}
}

func (_c *MockIndexer_Index_Call[T]) Run(run func(v *T, set bool)) *MockIndexer_Index_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*T), args[1].(bool))
	})
	return _c
}

func (_c *MockIndexer_Index_Call[T]) Return(rawKVPairs []badgerutils.RawKVPair, err error) *MockIndexer_Index_Call[T] {
	_c.Call.Return(rawKVPairs, err)
	return _c
}

func (_c *MockIndexer_Index_Call[T]) RunAndReturn(run func(v *T, set bool) ([]badgerutils.RawKVPair, error)) *MockIndexer_Index_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Lookup provides a mock function for the type MockIndexer
func (_mock *MockIndexer[T]) Lookup(args ...any) (badgerutils.Iterator[[]byte, indexing.Chunk], error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Lookup")
	}

	var r0 badgerutils.Iterator[[]byte, indexing.Chunk]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]any) (badgerutils.Iterator[[]byte, indexing.Chunk], error)); ok {
		return returnFunc(args)
	}
	if returnFunc, ok := ret.Get(0).(func(...any) badgerutils.Iterator[[]byte, indexing.Chunk]); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(badgerutils.Iterator[[]byte, indexing.Chunk])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...any) error); ok {
		r1 = returnFunc(args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIndexer_Lookup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookup'
type MockIndexer_Lookup_Call[T any] struct {
	*mock.Call
}

// Lookup is a helper method to define mock.On call
//   - args
func (_e *MockIndexer_Expecter[T]) Lookup(args ...interface{}) *MockIndexer_Lookup_Call[T] {
	return &MockIndexer_Lookup_Call[T]{Call: _e.mock.On("Lookup",
		append([]interface{}{}, args...)...)}
}

func (_c *MockIndexer_Lookup_Call[T]) Run(run func(args ...any)) *MockIndexer_Lookup_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockIndexer_Lookup_Call[T]) Return(iterator badgerutils.Iterator[[]byte, indexing.Chunk], err error) *MockIndexer_Lookup_Call[T] {
	_c.Call.Return(iterator, err)
	return _c
}

func (_c *MockIndexer_Lookup_Call[T]) RunAndReturn(run func(args ...any) (badgerutils.Iterator[[]byte, indexing.Chunk], error)) *MockIndexer_Lookup_Call[T] {
	_c.Call.Return(run)
	return _c
}
